[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.6.1"
semver = "1.0.16"
uuid = { version = "1.2.2", features = ["v4", "serde"] }
